config/routes.rb
Rails.application.routes.draw do
  mount Blorgh::Engine, at: "/blog"
  root 'articles#home'
  get '/articles/about', to: 'articles#about'
  get '/articles/signup', to: 'articles#signpage'
  get '/articles/login', to: 'articles#loginpage'
  post '/articles/signup', to: 'articles#signpage_new'
  post '/articles/login', to: 'articles#loginpage_new'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    #belongs_to :create
    validates :title, presence: true
    validates :description, presence: true
    
end

app/models/create.rb
class Create < ApplicationRecord
    has_many :articles
    validates :username, :password, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
end

app/models/project.rb
class Project < ApplicationRecord
    validate :username, :password, presence: true
    validate :email, presence: true,uniqueness: true, format:{ with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email'}
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ActionController::Base
    def home
    end
    def about
    end
   def show
       @articles=Article.find(params[:id])
   end
   def index
       @articles=Article.all
   end
   
   def new
       @article=Article.new
   end
   def edit
     @article=Article.find(params[:id]) 
   end
   def create
       @article=Article.new(params.require(:article).permit(:title,:description))
           if @article.save
               redirect_to @article
           else
               render 'new'
           end
   end
   def update
       @article=Article.find(params[:id])
       if @article.update(params.require(:article).permit(:title,:description))
          flash[:notice]="Article was updated"
          redirect_to @article
       else
          render 'edit'
       end
   end
   def destroy
      @articles=Article.find(params[:id]) 
      @articles.destroy
      redirect_to articles_path
   end
   def signup
   end
   def signpage
   end
   def signpage_new
    if params!=nil
     (@creates=Create.new(username:params[:username],password:params[:password],email:params[:email]))
    end
     if @creates.save
       CreateMailer.welcome_email(@creates).deliver
       #@create=Create.find_by(params[:username])
       @authentication_sign="successfully created account"
       render :'authentication_sign'
     else
       @authentication="failed"
       render :'authentication'
    end
    end
    def loginpage
    end
    def loginpage_new
        @status=false
        if params!=nil
            if((params[:username]!=nil) && (params[:password]!=nil) && (params[:email]!=nil))
                @creates=Create.where(username:params[:username],email:params[:email])
                @creates.each do |f|
                    if((f.username==params[:username]) && (f.password==params[:password]) && (f.email==params[:email]))
                        @status=true
                    end
                end
            end
        end
        if @status==true
            @authentication_login="login success"
            render :'authentication_login'
        else
            @authentication="login failed"
            render :'authentication'
        end
    end
end

app/controllers/creates_controller.rb
class CreatesController < ApplicationController
  before_action :set_create, only: %i[ show edit update destroy ]

  # GET /creates or /creates.json
  def index
    @creates = Create.all
  end

  # GET /creates/1 or /creates/1.json
  def show
  end

  # GET /creates/new
  def new
    @create = Create.new
  end

  # GET /creates/1/edit
  def edit
  end

  # POST /creates or /creates.json
  def create
    @create = Create.new(create_params)

    respond_to do |format|
      if @create.save
        format.html { redirect_to @create, notice: "Create was successfully created." }
        format.json { render :show, status: :created, location: @create }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @create.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creates/1 or /creates/1.json
  def update
    respond_to do |format|
      if @create.update(create_params)
        format.html { redirect_to @create, notice: "Create was successfully updated." }
        format.json { render :show, status: :ok, location: @create }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @create.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creates/1 or /creates/1.json
  def destroy
    @create.destroy
    respond_to do |format|
      format.html { redirect_to creates_url, notice: "Create was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create
      @create = Create.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def create_params
      params.require(:create).permit(:username, :password, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
     def home
     end
     def about
     end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def signup
  end

  def signpage
  end

  def loginpage
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/creates_helper.rb
module CreatesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/about.html.erb
<center>
<h1 class="city">Articles to generate</h1>
<a href="http://127.0.0.1:3000/articles"  target="_self" ><button>Todo_list</button></a>
<p><%= link_to 'Back to home', root_path %></p>
</center>
<style>
.city{background-color:purple;color:white;padding:15px}
a:link, a:visited{ background-color:skyblue;
                   color:white;
                   padding: 15px 25px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>

app/views/articles/authentication.html.erb
<body>
<style>
.city{background-color:tomato;color:white;padding:10px}
</style>
<p>
<center><h1 class="city">Failed</h1></center>
</p>
<%= link_to "Home", root_path %>
</body>

app/views/articles/authentication_login.html.erb
<center>
<h1 class="text">Login successfully</h1>
<a href="http://127.0.0.1:3000/articles/about"  target="_self" ><button>ARTICLES</button></a>
<a href="http://127.0.0.1:3000/articles/login"  target="_self" ><button>Logout</button></a>
<style>
.text{background-color:orange;color:black;padding:10px}
a:link, a:visited{ background-color:skyblue;
                   color:white;
                   padding: 30px 35px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>
</center>

app/views/articles/authentication_sign.html.erb
<h1>Signup successfully</h1>
<a><%= link_to 'Login', articles_login_path %></a>
<style>
a:link, a:visited{ background-color:skyblue;
                   color:white;
                   padding: 15px 25px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>

app/views/articles/edit.html.erb
<center>
<h1 class="text">Edit article</h1></center>
<% if @article.errors.any? %>
   <h2> the following errors are to be prevented </h2>
    <ul>
       <% @article.errors.full_messages.each do |f| %>
          <li> <%= f %> </li>
       <% end %>
    </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>
    <p>
       <%= f.label :title %><br>
       <%= f.text_field  :title %>
    </p>
    <p>
       <%= f.label :description %><br>
       <%= f.text_field  :description %>
    </p>
    <p class="city">
       <%= f.submit %>
    </p>
<% end %>
<p class="city"><button><%= link_to 'Cancel and return to articles', articles_path %></button></p>
<style>
.text{background-color:purple;color:white;padding:15px}
.city{background-color:skyblue;
      color:white;
      padding: 5px 10px;
      text-align:center;
      text-decoration:none;
      display:inline-block;}

</style>
</center>

app/views/articles/home.html.erb
<h1>This is home page</h1>
<%= link_to 'Return to articles', articles_path %>
<%= link_to 'About page', about_path %>

app/views/articles/index.html.erb
<center>
<h1>Articles listing</h1>
<table>
<thead>
<style>
.city{background-color:orange;color:red;padding:10px}
</style>
<tr>
   <th class="city"> Title </th>
   <th class="city"> Description </th>
   <th class="city" colspan="3"> Action </th>
</tr>
</thead>
<tbody>
    <% @articles.each do |article| %>
        <style>
        .text{background-color:skyblue;color:blue;padding:15px}
        .input{background-color:skyblue;color:black;padding:15px}
        </style>
       <tr>
           <td class="input"><%= article.title %></td>
           <td class="input"><%= article.description %></td>
           <td class="text"><%= link_to 'Show', article_path(article) %></td>
           <td class="text"><%= link_to 'Edit', edit_article_path(article) %></td>
       </tr>
    <% end %>
</tbody>
</table>
<p>
<%= link_to 'Create new article', new_article_path %>
</p>
<a href="http://127.0.0.1:3000/articles/login"  target="_self" ><button>Logout</button></a>
<style>
a:link, a:visited{ background-color:lightblue;
                   color:purple;
                   padding: 15px 25px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>
</center>

app/views/articles/loginpage.html.erb
<center>
<h1 class="text">Welcome to loginpage</h1>
<div class="container">
<%= form_with model: @create do|t|%>
    
    <%= t.label :username,"Username"%>
    <%= t.text_field :username, placeholder: "Enter username" %><br><br>
    
    <%= t.label :password,"Password"%>
    <%= t.password_field :password, placeholder: "Enter password" %><br><br>
    
    <%= t.label :email,"Email"%>
    <%= t.text_field :email, placeholder: "Enter email" %><br><br>

    <p class="city"><%= t.submit %></p>

    <% end %>
</div>
<style>
.text{background-color:purple;color:white;padding:15px}
.city{background-color:green;
      color:white;
      padding: 5px 10px;
      text-align:center;
      text-decoration:none;
      display:inline-block;}
</style>
<div class="container" style="background-color:#f1f1f1"></div>
<p>If you new user click here <%= link_to "User", articles_signup_path %></p>
</center>

app/views/articles/new.html.erb
<center><h1 class="test">New article</h1></center>
<p class="text"><%= link_to 'Dashboard', articles_about_path %></p>
<% if @article.errors.any? %>
   <h2> the following errors are to be prevented </h2>
    <ul>
       <% @article.errors.full_messages.each do |f| %>
          <li> <%= f %> </li>
       <% end %>
    </ul>
<% end %>
<%= form_with scope: :article, url: articles_path, local: true do |f| %>
<p>
<%= f.label :title %><br>
<%= f.text_field  :title %>
</p>
<p>
<%= f.label :description %><br>
<%= f.text_field  :description %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>
<%= link_to 'Return to articles', articles_path %>
<style>
.test{background-color:purple;color:white;padding:15px}
.text{background-color:skyblue;color:black;}
a:link, a:visited{ background-color:skyblue;
                   color:white;
                   padding: 5px 10px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>

app/views/articles/show.html.erb
<center><h1 class="test"> Showing article</h1></center>
<p class="text"><%= link_to 'Dashboard', articles_about_path %></p>
<p><strong> Title:</strong><%= @articles.title %></p>
<p><strong>Description: </strong><%= @articles.description %></p>
<p><button><%= link_to 'Edit',  edit_article_path(@articles) %> </button></p>
<p><button><%= link_to 'Return to articles', articles_path %></button></p>
<style>
.test{background-color:purple;color:white;padding:15px}
.text{background-color:skyblue;color:black;}
a:link, a:visited{ background-color:skyblue;
                   color:black;
                   padding: 5px 10px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>

app/views/articles/signpage.html.erb
<center>
<h1 class="test">Welcome to signup_page</h1>
<div class="container">
<%= form_with model: @create do|t|%>
    
    <%= t.label :username,"Username"%>
    <%= t.text_field :username, placeholder: "Enter username" %><br><br>
    
    <%= t.label :password,"Password"%>
    <%= t.password_field :password, placeholder: "Enter password" %><br><br>
    
    <%= t.label :email,"Email"%>
    <%= t.text_field :email, placeholder: "Enter email" %><br><br>

    <p class="city"><%= t.submit %></p>

    <% end %>
</div>
<style>
.test{background-color:purple;color:white;padding:15px}
.city{background-color:tomato;
      color:white;
      padding: 5px 10px;
      text-align:center;
      text-decoration:none;
      display:inline-block;}
</style>
<div class="container" style="background-color:#f1f1f1"></div>
<p>If you new user click here <%= link_to "User", articles_login_path %></p>
</center>

app/views/articles/signup.html.erb
<center>
<h1>Welcome to VIT</h1>
<p> New user</p>
<a href="http://127.0.0.1:3000/articles/sign"  target="_self" ><button>signup</button></a>
<p>If already have an account</p>
<a href="http://127.0.0.1:3000/articles/login"  target="_self"><button>login</button></a>
</center>
<style>
a:link, a:visited{ background-color:skyblue;
                   color:white;
                   padding: 15px 25px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>

app/views/creates/_form.html.erb
<%= form_with(model: create) do |form| %>
  <% if create.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(create.errors.count, "error") %> prohibited this create from being saved:</h2>

      <ul>
        <% create.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/creates/edit.html.erb
<h1>Editing Create</h1>

<%= render 'form', create: @create %>

<%= link_to 'Show', @create %> |
<%= link_to 'Back', creates_path %>

app/views/creates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Creates</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creates.each do |create| %>
      <tr>
        <td><%= create.username %></td>
        <td><%= create.password %></td>
        <td><%= create.email %></td>
        <td><%= link_to 'Show', create %></td>
        <td><%= link_to 'Edit', edit_create_path(create) %></td>
        <td><%= link_to 'Destroy', create, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create', new_create_path %>

app/views/creates/new.html.erb
<h1>New Create</h1>

<%= render 'form', create: @create %>

<%= link_to 'Back', creates_path %>

app/views/creates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @create.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @create.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @create.email %>
</p>

<%= link_to 'Edit', edit_create_path(@create) %> |
<%= link_to 'Back', creates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<center>
<h1>This is home page</h1>
<p> New user</p>
<a href="http://127.0.0.1:3000/books/signup"  target="_self" ><button>signup</button></a>
<p>If already have an account</p>
<a href="http://127.0.0.1:3000/books/login"  target="_self"><button>login</button></a>
</center>
<style>
a:link, a:visited{ background-color:skyblue;
                   color:white;
                   padding: 15px 25px;
                   text-align:center;
                   text-decoration:none;
                   display:inline-block;}
a:hover, a:active{background-color:pink;}
</style>
</center>

app/views/projects/loginpage.html.erb
<h1>Projects#loginpage</h1>
<p>Find me in app/views/projects/loginpage.html.erb</p>

app/views/projects/signpage.html.erb
<h1>Projects#signpage</h1>
<p>Find me in app/views/projects/signpage.html.erb</p>

app/views/projects/signup.html.erb
<h1>Projects#signup</h1>
<p>Find me in app/views/projects/signup.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.title %></td>
        <td><%= user.text %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @user.text %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>